### PR TITLE
CORE-412: update model/messaging, mount irods config

### PR DESCRIPTION
**Pull request by ianmcorvidae**
This should be what's needed to switch road-runner back to using the `--config` option for porklock as is being added back in https://github.com/cyverse-de/porklock/pull/5

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
turns out it's actually pretty hard to test this stuff, but I'm seeing if I can figure something out, heh

**Comment by ianmcorvidae** [comment]
I updated this branch to include @slr71 changes to use go modules.

**Review by slr71 — APPROVED** [review]
Looks good to me. :shipit:

**Review by psarando — APPROVED** [review]
LGTM 👍

**Pull request merged**
